// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnooiopqwzunhqpzlmxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhub29pb3Bxd3p1bmhxcHpsbXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NDc4ODksImV4cCI6MjA1MDQyMzg4OX0.nf8zDuk0TDV5jGc-OqaUUgbcODOaOTwWg0c-3GrNdO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);